version: '3'

services:
  nameparse:
    build:
      dockerfile: Dockerfile
      context: .
    image: us.gcr.io/ivy-re-data/ivy-parser:0.0.1
    environment:
      - DEBUG
    command: pipenv run gunicorn main:app -w 3 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
