apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivy-parser
  namespace: default
spec:
  selector:
    matchLabels:
      app: ivy-parser
  template:
    metadata:
      labels:
        app: ivy-parser
    spec:
      containers:
        - name: ivy-parser
          image: us.gcr.io/ivy-re-data/ivy-parser:$VERSION
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "2m"
              memory: "5Gi"
          livenessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ivy-parser
  namespace: default
spec:
  selector:
    app: ivy-parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
