apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivy-parser
  namespace: default
spec:
  selector:
    matchLabels:
      app: ivy-parser
  template:
    metadata:
      labels:
        app: ivy-parser
    spec:
      containers:
        - name: ivy-parser
          image: us.gcr.io/ivy-re-data/ivy-parser:$VERSION
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "2m"
              memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ivy-parser
  namespace: default
spec:
  selector:
    app: ivy-parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
